### PR TITLE
Minimize db calls

### PR DESCRIPTION
**Pull request by obennet**
Minimized simulation db calls to 4 instead of thousands

### CODE REVIEW

**Comment by johnmartins** [comment]
Good work! I'll target this PR for version 1.0.6, which will contain some other small fixes

**Comment by johnmartins** [comment]
@obennet I'm not sure this patch performs as intended. I just had two simulation tests fail, and around 900 calls to the database. See logs from merge here: https://github.com/sed-group/sed-backend/actions/runs/5260000227/jobs/9506326689

Merge has been reverted for now

**Comment by obennet** [comment]
@johnmartins The large amount of db calls is unfortunately due to the tests and also the tests does not fail for me so I believe that it once again is a problem with the tests. I'm going on a 2 weeks vacation starting tomorrow so I think that I will have to rewrite all the tests when I get back because this is not sustainable.

**Comment by johnmartins** [comment]
I took a close look at the log files, and I think I have found the issue I'm seeing with large amounts of database calls. 

Problem line: https://github.com/sed-group/sed-backend/blame/86467d9e8e8e5f06549cfbf3c4fef90bc3a3f634/sedbackend/apps/cvs/link_design_lifecycle/storage.py#LL114C46-L114C46

It calls "populate_formula" (https://github.com/sed-group/sed-backend/blame/86467d9e8e8e5f06549cfbf3c4fef90bc3a3f634/sedbackend/apps/cvs/link_design_lifecycle/storage.py#L117), which itself runs two db-calls per function call. Since it is a for-loop, it runs 2*n db-calls, and n seems to be large. 

To make sure I also took a quick look at your tests for the simulation, and I did not see anything suspicious that might be causing the db-traffic. I think "populate_formula" is the villain, here. It should not be inside of a for-loop since it only selects data which.

But I could not help out with finding the cause of the random errors since I do not really understand the CVS stuff. For that, perhaps rewriting the failing tests (there seems to be two of them) a bit more carefully is the best option.

**Pull request merged**
