### PR TITLE
Fixed test fail and bumped up desim version

### PR DESCRIPTION
**Pull request by obennet**
We're still working on the rest of the mandatory fixes you listed but this was a small fix that will have a big impact.

### CODE REVIEW

**Comment by johnmartins** [comment]
Looks good. Just one small comment. If you fix that, then it is ready to merge.

**Comment by obennet** [comment]
Sorry but I can't find the comment. What do I have to fix?

**Comment by johnmartins** [comment]
Submitted the comment (forgot to save it the first time) and changed merge target to the branch for version 1.0.4 (#87)

**Comment by johnmartins** [comment]
Is this ready for merging with version 1.0.4?

**Comment by obennet** [comment]
Yes, the comment has been fixed now

**Pull request merged**
